### PR TITLE
Add citation file

### PR DESCRIPTION
**Pull request by tcmetzger**
Add CITATION.cff to repo

### CODE REVIEW

**Comment by RobertPincus** [comment]
@tcmetzger Seems to be the authors here should be you, @makepath-alex , and @sehnem, not the current list

**Comment by sehnem** [comment]
@tcmetzger in case you need, my orcid is https://orcid.org/0009-0004-9403-1509

**Comment by tcmetzger** [comment]
@RobertPincus I have listed you and makepath as the authors of pyRTE-RRTMGP. I'm listing the original RTE+RRTMGP as a reference (with the full list of authors), the "Balancing Accuracy, Efficiency, and Flexibility in Radiation Calculations for Dynamical Models" is a second reference. I hope this is all correct, feel free to commit changes or suggest edits!

We also don't have a DOI for pyRTE-RRTMGP (yet) - do you think that would make sense, would you like to add one?

**Comment by RobertPincus** [comment]
Ah ok thanks @tcmetzger  for the explanation. 

Yes we should get a DOI for the Python front end. This is something I should do?

**Comment by tcmetzger** [comment]
@RobertPincus It would be great if you could do that (I could do that tomorrow or Wednesday if you don't have the time)!

**Pull request merged**
